modLoader="javafml"
loaderVersion="[36,)"
license="Apache Public License v2"
[[mods]]
    displayName="DataGenerator"
    modId="data_generator"
    version="1.0.0"
    authors="dags"
    description="GameData generator"
    